### ISSUE TITLE
Premios ACM UPV?

### ISSUE THREAD

**Issue by a1ex9788** [RodrigoLlanes/AdventOfCode2020#1]
Hola, ¿sabes si hay premios en esto del ranking del Advent of Code de la UPV? De ser así, ¿sabes qué puestos son premiados y cuales son los premios? Gracias.

**Comment by RodrigoLlanes** [comment]
Buenas, el año pasado si que había premios para los 5 primeros, pero este
año, que yo sepa, no han dicho nada

**Comment by RodrigoLlanes** [comment]
Puedes ponerte en contacto con ACM upv por Instagram y preguntar

**Comment by a1ex9788** [comment]
Okay, gracias. Me dijeron que sí habrá pero no es seguro. Por otro lado, ¿puedes eliminar este issue para k deje de salirme este repositorio en mi perfil? gracias :)
